### ISSUE TITLE
Browse Page Crashing

### ISSUE THREAD

**Issue by 0xKoda** [CosmosContracts/old-website#139]
<img width="1432" alt="Screen Shot 2022-10-21 at 10 00 41 pm" src="https://user-images.githubusercontent.com/88812262/197191030-44adcf69-0a36-4fa7-95c5-1a2a96cd0079.png">

https://www.junonetwork.io/ecosystem/#browse

Browse page document crashes on both firefox and chromium based browsers.
Replicated:

- FireFox
- Brave 
- Chrome

**Comment by nullmames** [comment]
@CamelJuno Can you plaese have a look

**Comment by CosmosCamel** [comment]
Fixed #140
